# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2

     - name: FTP Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
       uses: SamKirkland/FTP-Deploy-Action@4.0.0
       with:
          # ftp server
          server: ${{ secrets.ftp_server }}
          # ftp username
          username: ${{ secrets.ftp_user }}
          # ftp password
          password: ${{ secrets.ftp_password }}
          # Server port to connect to (read your web hosts docs)
          #port: 1 # optional
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          #protocol: 1 # optional
